"""expand_schema_bookmarks_externships

Revision ID: 489bb7154375
Revises: 0b4bae5b7920
Create Date: 2026-02-12 23:11:20.918068
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489bb7154375'
down_revision: Union[str, None] = '0b4bae5b7920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_user_opportunity_bookmark')
    )
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    op.create_index(op.f('ix_bookmarks_opportunity_id'), 'bookmarks', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('externships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', name='externshipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_externships_id'), 'externships', ['id'], unique=False)
    op.create_index(op.f('ix_externships_student_id'), 'externships', ['student_id'], unique=False)
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('tagline', sa.String(length=300), nullable=True))
    op.add_column('opportunities', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_opportunities_is_active'), 'opportunities', ['is_active'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('nim', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('cv_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_nim'), 'users', ['nim'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nim'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'cv_url')
    op.drop_column('users', 'nim')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_opportunities_is_active'), table_name='opportunities')
    op.drop_column('opportunities', 'is_active')
    op.drop_column('companies', 'tagline')
    op.drop_column('companies', 'instagram_url')
    op.drop_column('companies', 'linkedin_url')
    op.drop_column('companies', 'founded_year')
    op.drop_column('companies', 'employee_count')
    op.drop_index(op.f('ix_externships_student_id'), table_name='externships')
    op.drop_index(op.f('ix_externships_id'), table_name='externships')
    op.drop_table('externships')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_opportunity_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
